// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupplierTestApp.Domain.Entities;

namespace SupplierTestApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SupplierTestApp.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SupplierName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SupplierNumber");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("SupplierTestApp.Entities.SupplierRate", b =>
                {
                    b.Property<int>("SupplierRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SupplierNumber")
                        .HasColumnType("int");

                    b.HasKey("SupplierRateId");

                    b.HasIndex("SupplierNumber");

                    b.ToTable("SupplierRate");
                });

            modelBuilder.Entity("SupplierTestApp.Entities.SupplierRate", b =>
                {
                    b.HasOne("SupplierTestApp.Entities.Supplier", "Supplier")
                        .WithMany("FK_SupplierRate")
                        .HasForeignKey("SupplierNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("SupplierTestApp.Entities.Supplier", b =>
                {
                    b.Navigation("FK_SupplierRate");
                });
#pragma warning restore 612, 618
        }
    }
}
